### PR TITLE
done Backend PD (with fix after done UI)

### PR DESCRIPTION
**Pull request by Kien-Huy**

### CODE REVIEW

**Comment by NguyenQuocAnDev27** [comment]
error UI:
image
error nav to ProjectDetail:
image
change UI:
X button change to red color; close button change to light gray color
image

**Comment by Kien-Huy** [comment]
to fix error nav to ProjectDetail: (update SQL)

**Comment by Kien-Huy** [comment]
fix

**Comment by NguyenQuocAnDev27** [comment]
wrong name col. it should look like this
image

**Comment by NguyenQuocAnDev27** [comment]
image

**Comment by NguyenQuocAnDev27** [comment]
Comment all line SecretKeyController.java

**Pull request merged**
